theme: jekyll-theme-hacker
title: UoL CyberSoc
description: " Liverpool's premiere cyber security society"
me_url: https://www.cybersoc.cf
discord_url: https://invite.gg/cybersoc
liverpoolguild_url: https://www.liverpoolguild.org/groups/cyber-security
resources_url: https://www.cybersoc.cf/resources.html
twitter_url: https://twitter.com/cybersocuol