theme: jekyll-theme-hacker
title: UoL CyberSoc
description: One place for all your security needs.
me_url: https://www.cybersoc.cf
discord_url: https://discordapp.com/invite/p6qGd3D
liverpoolguild_url: https://www.liverpoolguild.org/groups/cyber-security
resources_url: ./resources
