theme: jekyll-theme-hacker
title: UoL CyberSoc
description: Liverpool's premiere cyber security society
me_url: https://www.cybersoc.cf
discord_url: https://discordapp.com/invite/p6qGd3D
liverpoolguild_url: https://www.liverpoolguild.org/groups/cyber-security
twitter_url: https://twitter.com/cybersocuol
resources_url: https://www.cybersoc.cf/resources.html
