theme: jekyll-theme-hacker
title: UoL CyberSoc
description: One place for all your security needs.
discord_url: https://discordapp.com/invite/p6qGd3D
liverpoolguild_url: https://www.liverpoolguild.org/groups/cyber-security
